language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "node"
  - "stable"
  - "iojs"
before_install:
  npm install codecov.io istanbul -g
script:
  istanbul cover ./node_modules/.bin/jasmine && cat ./coverage/lcov.info | codecov
